name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: UjjS
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and push the changes
        run: |
          git config user.name "Ujjwal Shikhar"
          git config user.email "shikharujjwal@gmail.com"
          git add github-contribution-grid-snake.svg
          git commit -m "🐍 Update GitHub contribution grid snake"
          git push https://UjjS:${{ secrets.PAT }}@github.com/UjjS/UjjS.git HEAD:main
