name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: UjjS
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 Generate GitHub contribution grid snake"
          add: "github-contribution-grid-snake.svg"
