name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: UjjS
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.PAT }}
            branch: main
            force: true

